ma_gnole/config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  resources :places, only:[:index, :show] do
    resources :places_reviews, only: [:new, :create, :destroy]
    resources :bookings, only: [:new, :create]
  end
  devise_for :users
  namespace :account do

    resources :places do
      resources :places_reviews, only: [:new, :create, :destroy]
    end
    resources :bookings, only: [:index, :show, :destroy]
    resources :availibilities, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :refused
        put :refused
        get :accepted
        put :accepted
      end
    end
    resource :profile, only: [:show, :update, :edit], controller: :profile
  end
  resources :profiles, only: [:show] do
  end
  resources :users_reviews, only: [:new, :create]
end

ma_gnole/app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :availibilities, dependent: :destroy
  has_many :place_reviews, dependent: :destroy
  has_many :user_reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :name, presence: :true
  validates :address, presence: :true
  validates :description, presence: :true
  validates :price, numericality: { only_integer: true }, presence: :true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

ma_gnole/app/controllers/account/places_controller.rb
class Account::PlacesController < ApplicationController

  def index

     if params[:nbrPersons] != "" && params[:nbrPersons] != nil
      @places = Place.where("nbr_person >= ?", params[:nbrPersons])
    else
      @places = Place.all
    end

    if params[:checkin] != "" && params[:checkin] != nil
      @places = @places.select do |place|
        if place.availibilities.where("start_date >= ?", params[:checkin] ).length > 0
          true
        end
      end
    end


    if params[:checkout] != "" && params[:checkout] != nil


      @places = @places.select do |place|
        if place.availibilities.where("end_date <= ?", params[:checkout] ).length > 0
          true
        end
      end
    end

    if params[:location] != "" && params[:location] != nil
      if Place.near(params[:location], 50).length > 0
        @places = Place.near(params[:location], 50)
      end
    end

    @markers = []
    @places.each do |place|
     if place.latitude && place.longitude
      @markers << {
        lat: place.latitude,
        lng: place.longitude,
        infowindow: place.name
        }
     end
    end



  end


  def show
    @place = Place.find(params[:id])
    @place_reviews = @place.place_reviews
    @place_coordinates = { lat: @place.latitude, lng: @place.longitude }
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    if @place.save
      redirect_to account_place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to account_places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description, :photo, :nbr_person, :price)
  end

end

ma_gnole/app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @params = params
    @places = Place.all
    if params[:nbrPersons].present?

      @places = Place.where("nbr_person >= ?", params[:nbrPersons])
    end


    if params[:location].present?
      @places = @places.near(params[:location], 50)

    end
# le select ici execute les requetes sql stockées au dessus,
# si pas de select c'est à l'affichage dans le html que les requetes sont réolues
    if params[:checkin].present? && params[:checkout].present?
      availables_places = []
      @places.each do |place|
        available = true
        place.availibilities.each do |a|
          if a.start_date <= params[:checkout].to_date || a.end_date <= params[:checkin].to_date
            available = false
          end
        end
        availables_places << place if available
      end
      @places = availables_places
    end

    if params[:price].present?
      #TODO
    end

    @markers = []
    @places.each do |place|
     if place.latitude && place.longitude
      @markers << {
        lat: place.latitude,
        lng: place.longitude,
        infowindow: "<a href=#{place_path(place)}><h2>#{place.name}</h2><h3>#{place.address}</h3><p><img src='#{place.photo}' height='200'></p>"
        }
     end
    end



  end

  def show
    @place = Place.find(params[:id])
    @place_reviews = @place.place_reviews


    @markers = []
     if @place.latitude && @place.longitude
      @markers << {
        lat: @place.latitude,
        lng: @place.longitude,
        infowindow: "<h1>#{@place.name}</h1><h2>#{@place.address}</h2><p><img src='#{@place.photo}' height='200'></p>"
        }
     end

  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to account_place_path(@place)
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    if @place.save
      redirect_to account_place_path(@place)
    else
      render :edit
    end

  end

  def destroy
    @place = Place.find(params[:id])
    @place.delete
    redirect_to account_places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description, :photo, :nbr_person)
  end


end

ma_gnole/app/views/places/index.html.erb
<%= render partial: 'pages/searchbar', locals: {params: @params} %>


<div class="media">
  <div class="media-body">
    <div class="media-section">
      <div class="container">
        <div class="row">
        <h1 class="text-center">Your places list</h1>

          <% @places.each do |place| %>
            <div class="col-xs-12 col-sm-4">
              <div class="card text-center">

                <% if place.photo %>
                  <div class="card"
                    style="background-image: linear-gradient(rgba(0,0,0,0.3),
                     rgba(0,0,0,0.2)), url('<%= image_path place.photo %>')">
                <% else %>
                  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                <% end %>

                <div class="card-description">
                    <h2>pour <%= place.nbr_person %> personnes</h2>
                    <p><%= place.address %></p>
                  </div>

                  <div class=“card-description”>
                        <h3><%= link_to place.name, place_path(place) %></h3>
                    </div>
                  <a class=“card-link” href=“#” ></a>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="media-aside">
    <div class="media-section">
      <% if @places != [] && @places != nil && @places != "" %>
      <div id="map"></div>
      <% end %>
    </div>
  </div>
</div>
</div>

<style type="text/css">

      #map {
        display: flex;
        height: 100vh;
        width: 100%;
      }
    </style>

<!-- pour récupérer le javascript -->
<%= content_for :after_js do %>
<!-- le raw est pour empecher l'échappement du tableau passé en argument et converti en json ici (verif en console sans le raw pour voir la différence) -->
    <script type="text/javascript">
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
    </script>

<% end %>

ma_gnole/app/views/places/show.html.erb
<div class="media">

  <div class="media-body">
    <div class="media-section">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
      url(<%= image_path "vineyard.jpg" %>)">
        <div class="card-name">
          <h2><%= @place.name %></h2>
        </div>
        <div class="card-description">
          <h3><%= @place.address%></h3>
        </div>
        <div class="card-user avatar">
          <%= image_tag "logo.png" %>
        </div>
        <a class="card-link" href="#" ></a>
      </div>
    </div>

    <div class="media-section">
      <h2>Description</h2>
      <%= @place.description %>
    </div>
    <% @place_reviews.each do |review|%>
    <div class="media-section">


      <h3>Comment</h3>
      <%= review.description %>
      <h3>Ratings</h3>

      <%= review.rating %>
    </div>
    <% end %>
  </div>

  <div class="media-aside">
    <div class="media-section">

      <h3>Prix/j</h3>
      <%= @place.price %>

    </div>
    <div class="media-section">
       <h3>Dates non disponibles</h3>
        <% @place.availibilities.each do |availibility| %>
          <p> Non disponible du <%= availibility.start_date.strftime("%d %m %Y") %> au <%= availibility.end_date.strftime("%d %m %Y")%></p>
      <% end %>

    </div>



    <%= link_to "Book now", new_place_booking_path(@place), class: "btn btn-primary" %>

    <div class="media-section">
      <div id="map"> </div>
    </div>

  </div>
</div>






<style type="text/css">

      #map {
        display: flex;
        height: 100vh;
        width: 100%;
      }
    </style>

<!-- pour récupérer le javascript -->
<%= content_for :after_js do %>
<!-- le raw est pour empecher l'échappement du tableau passé en argument et converti en json ici (verif en console sans le raw pour voir la différence) -->
    <script type="text/javascript">
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
    </script>

<% end %>