ma_gnole/config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  resources :places, only:[:index, :show] do
    resources :places_reviews, only: [:new, :create, :destroy]
    resources :bookings, only: [:new, :create]
  end
  devise_for :users
  namespace :account do

    resources :places do
      resources :places_reviews, only: [:new, :create, :destroy]
    end
    resources :bookings, only: [:index, :show, :destroy]
    resources :availibilities, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :refused
        put :refused
        get :accepted
        put :accepted
      end
    end
    resource :profile, only: [:show, :update, :edit], controller: :profile
  end
  resources :profiles, only: [:show] do
  end
  resources :users_reviews, only: [:new, :create]
end

ma_gnole/app/views/pages/_searchbar.html.erb
<div id="mySearchBar" class="search_bar">
  </div>
    <div class="search">
        <div class="container">
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="form-section">
                <div class="row">
        <!-- on précise que c'est une méthode get sur le formulaire (pas de sauvegarde de données en db) et on pass la route de destination en action du formulaire-->
        <!-- account_places_path -->
            <form role="form" method="get" action="<%= places_path %>">
              <div class="col-md-4">
                <div class="form-group">
                  <label class="sr-only" for="location">Location</label>
                  <% if params[:location].present? %>
                    <input type="text" value=<%= params[:location]%> class="form-control" name="location" placeholder="Where ?">
                  <% else %>
                    <input type="text" class="form-control" name="location" placeholder="Where ?">
                  <% end%>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <label class="sr-only" for="checkin">Check in</label>
                  <div class="input-group">
                    <input type="date" class="form-control" name="checkin" placeholder="Check in">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                  </div>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <label class="sr-only" for="checkout">Check out</label>
                  <div class="input-group">
                    <input type="date" class="form-control" name="checkout" placeholder="Check out">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                  </div>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <label class="sr-only" for="guest">Guest</label>
                  <input type="number" class="form-control" name="nbrPersons" placeholder="Number ?">
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label class="sr-only" for="location">Location</label>
                  <% if params[:price].present? %>
                    <input type="text" value=<%= params[:price]%> class="form-control" name="price" placeholder="Where ?">
                  <% else %>
                    <input type="number" class="form-control" name="price" placeholder="Max price">
                  <% end%>
                </div>
              </div>


              <div class="col-md-2">
                <button type="submit" class="btn btn-default btn-primary">Search</button>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

ma_gnole/app/views/pages/home.html.erb
<div class="banner" style="background: url('http://051b1de9e9ecc772c2d2-4491a5e521b7c42737795ca67148d758.r80.cf1.rackcdn.com/vogelzang-vineyard.jpg');">
      <div class="banner-content">
        <h1>LE BON VIGNOBLE</h1>
        <p>Découvrez notre sélection de vignobles à visiter aux meilleurs prix</p>
        <form method="get" action="<%= places_path %>" class="form-inline">
          <input type="text" class="form-control input-lg" placeholder="where ?" name="location">
          <input type="date" class="form-control input-lg" placeholder="checkin ?" name="checkin">
          <input type="date" class="form-control input-lg" placeholder="checkout ?" name="checkout">
          <input name="nbrPersons" class="form-control input-lg" placeholder="Number ?">
          <input type="submit" class="btn btn-primary btn-lg" value="Search">
        </form>
      </div>
</div>