ma_gnole/config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  resources :places, only:[:index, :show] do
    resources :places_reviews, only: [:new, :create, :destroy]
    resources :bookings, only: [:new, :create]
  end
  devise_for :users
  namespace :account do

    resources :places do
      resources :places_reviews, only: [:new, :create, :destroy]
    end
    resources :bookings, only: [:index, :show, :destroy]
    resources :availibilities, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :refused
        put :refused
        get :accepted
        put :accepted
      end
    end
    resource :profile, only: [:show, :update, :edit], controller: :profile
  end
  resources :profiles, only: [:show] do
  end
  resources :users_reviews, only: [:new, :create]
end

ma_gnole/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :status, presence: :true
end

ma_gnole/app/controllers/account/bookings_controller.rb
class Account::BookingsController < ApplicationController

  after_action :make_new_availability, only: [:accepted, :refused]

  def index
  end

  def show
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  # def update
  #   @article = Article.find(params[:id])
  #   @article.update(article_params)
  #   redirect_to articles_path(@articles)
  # end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to account_profile_path
  end

  def refused
    @booking = Booking.find(params[:id])
    @booking.status = "refused"
    @booking.save
    redirect_to account_profile_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  private

  def make_new_availability
    @booking = Booking.find(params[:id])
    @availibility = Availibility.new(price: 20, start_date: @booking.start_date, end_date: @booking.end_date, place_id: @booking.place_id)
    @availibility.save
  end
end

ma_gnole/app/controllers/bookings_controller.rb
  class BookingsController < ApplicationController

  before_action :authenticate_user!

  def new
    @place = Place.find(params[:place_id])
    @booking = Booking.new
  end

  def create
    @place = Place.find(params[:place_id])
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @days = diff_days(@booking.start_date, @booking.end_date).to_i
    @booking.price = @place.price * @days
    @booking.place = @place
    @booking.user = current_user
    if @booking.save!
      BookingMailer.confirm(@booking).deliver_now
      redirect_to places_path

    else
      render :new
    end
  end

  def diff_days(start_date, end_date)
    @nbr_days = end_date - start_date
  end

private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

ma_gnole/app/views/bookings/_form.html.erb
<%= simple_form_for(booking, url: place_bookings_path, method: :create) do |f| %>
  <%= f.error_notification %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.text_field :place_id, value: place_id, class: 'hidden' %>
  <%= f.button :submit %>
  <%end %>

ma_gnole/app/views/bookings/create.html.erb
<h2>Coucou</h2>

ma_gnole/app/views/bookings/new.html.erb
<h1>booking#new</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <%= simple_form_for(@booking, url: place_bookings_path) do |f| %>
        <%= f.error_notification %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.button :submit %>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-3">
      <h3>Reservez en un clic votre oenotour</h3>
    </div>
  </div>

</div>